site_key: 6LdAX-QUAAAAAMMnzyFFXELihbRUT-glryiQtR2h
secret_key: 6LdAX-QUAAAAAPwN8eTDPVWvyVspT_15tX7z2qP6
verify_hostname: false
use_globally: true
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
_core:
  default_config_hash: eKR4FfUD7Cp3bXamsCz6GAxh0PCLIZNMa65y2kChIh0
